_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 64
d:
    value: 10
dataset:
    value: Building
deeper:
    value: true
epochs:
    value: 500
experiment_name:
    value: Building_random_100
feature:
    value: AE
kernel:
    value: SM
kernel_mode:
    value: learned
kernel_param:
    value: 1
lr:
    value: 0.01
manual_lr:
    value: true
modality:
    value: PS-RGBNIR
mode:
    value: random
n_pins:
    value: 100
num_decoder:
    value:
        - 64
num_encoder:
    value:
        - 64
        - 32
num_runs:
    value: 1
r:
    value: 3
seed:
    value: 0
val_every_epoch:
    value: 5
